name: x_framework
description: A set of reusable widgets all started with X.
version: 0.0.1
homepage: https://github.com/codingwithsaeed/x_framework

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  another_flushbar: ^1.12.30
  flutter_screenutil: ^5.9.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/icons/
  fonts:
    - family: vazir
      fonts:
        - asset: assets/fonts/vazir.ttf
    - family: iransans
      fonts:
        - asset: assets/fonts/iransans.ttf